title: Blog
author: xinqiu
email: xinqiu.94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My new Blog.
# baseurl: "/jekyll-theme-kagami"
lang: zh-Hans # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: manni # this specifies color scheme for syntax highlighting
github_username: xinqiu
twitter_username: xinqiu_bot
instagram_username: xinqiu_bot
google_analytics: UA-57881840-1
disqus_shortname: xinqiu

# Build settings
markdown: kramdown
mathjax: true
# theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock